### ISSUE TITLE
[Feature Request] Add a toggle to disable block selection

### ISSUE THREAD

**Issue by Strange-Quark-007** [YukoganDev/HasteMod#1]
Add a toggle to  disable the selection of specific block for insta-mine. In turn allow all the instamine-able block.

When we mine underground we get mix of blocks like stone, granite, andesite diorite -all of which can be insta-mined.
If selected block setting is removed (i.e. allow user to toggle it) all the blocks can be insta-mined.

----
If we have mod that auto switches tools (say pickaxe to shovel) even dirt, sand can  also be insta-mined

This change will maximize the usefulness of the mod

**Comment by yukogan-gh** [comment]
Thank you a lot!
